services:
  web:
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_BASE=http://mizunie2.colopp.net:3000
    command: ["bash", "-lc", "npm ci --include=dev && npm run build && npm run start -- -p 3001 -H 0.0.0.0"]
